# Generated by Django 4.1.3 on 2022-11-13 10:15

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import swapper


# Heavily inspired by https://github.com/dj-stripe/dj-stripe/blob/master/djstripe/migrations/0001_initial.py

DYNAMIC_FILE_UPLOADED_BY_MODEL = getattr(settings, 'DYNAMIC_FILE_UPLOADED_BY', settings.AUTH_USER_MODEL)
DYNAMIC_FILE_UPLOADED_BY_DEPENDENT_MIGRATION = DYNAMIC_FILE_UPLOADED_BY_MODEL

DYNAMIC_FILE_UPLOADED_BY_MODEL_MODEL_MIGRATION_DEPENDENCY = getattr(
    settings, 'DYNAMIC_FILE_UPLOADED_BY_MIGRATION_DEPENDENCY', '__first__'
)

DYNAMIC_FILE_UPLOADED_BY_MODEL_DEPENDENCY = migrations.swappable_dependency(
    DYNAMIC_FILE_UPLOADED_BY_MODEL
)

if DYNAMIC_FILE_UPLOADED_BY_MODEL != settings.AUTH_USER_MODEL:
    DYNAMIC_FILE_UPLOADED_BY_MODEL_DEPENDENCY = migrations.migration.SwappableTuple(
        (
            DYNAMIC_FILE_UPLOADED_BY_MODEL.split('.', 1)[0],
            DYNAMIC_FILE_UPLOADED_BY_MODEL_DEPENDENCY,
        ),
        DYNAMIC_FILE_UPLOADED_BY_MODEL,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFileBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='A description for this file')),
                ('uploaded_by', models.ForeignKey(help_text='The owner/uploader of this file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=DYNAMIC_FILE_UPLOADED_BY_MODEL)),
            ]
        ),
    ]
