# Generated by Django 4.1.3 on 2022-11-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFile',
            fields=[
                ('dynamicfilebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_file.dynamicfilebase')),
                ('file', models.FileField(help_text='The uploaded file', storage='dynamic_file.storage.filesystem_storage', upload_to='')),
            ],
            bases=('dynamic_file.dynamicfilebase',),
        ),
    ]
