# Generated by Django 4.1.3 on 2022-11-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_file', '0001_initial'),
        ('test_app', '0002_testmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelOneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_to_one_file', to='dynamic_file.dynamicfile')),
            ],
        ),
    ]
